/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApieRouteImport } from './routes/apie'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EnRouteRouteImport } from './routes/en/route'
import { Route as KontaktaiRouteImport } from './routes/kontaktai'
import { Route as PaslaugosRouteImport } from './routes/paslaugos'
import { Route as PrivatumoPolitikaRouteImport } from './routes/privatumo-politika'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StraipsniaiRouteImport } from './routes/straipsniai'
import { Route as TaisyklesRouteImport } from './routes/taisykles'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApieIndexRouteImport } from './routes/apie.index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnApieRouteImport } from './routes/en/apie'
import { Route as EnKontaktaiRouteImport } from './routes/en/kontaktai'
import { Route as EnPaslaugosRouteImport } from './routes/en/paslaugos'
import { Route as EnPrivatumoPolitikaRouteImport } from './routes/en/privatumo-politika'
import { Route as EnTaisyklesRouteImport } from './routes/en/taisykles'
import { Route as PaslaugosIndexRouteImport } from './routes/paslaugos.index'
import { Route as PaslaugosSlugRouteImport } from './routes/paslaugos.$slug'
import { Route as StraipsniaiIndexRouteImport } from './routes/straipsniai.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminInquiriesRouteImport } from './routes/_authenticated/admin.inquiries'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as EnApieIndexRouteImport } from './routes/en/apie.index'
import { Route as EnPaslaugosIndexRouteImport } from './routes/en/paslaugos.index'
import { Route as EnPaslaugosSlugRouteImport } from './routes/en/paslaugos.$slug'
import { Route as AuthenticatedAdminWebsiteAboutRouteImport } from './routes/_authenticated/admin.website.about'
import { Route as AuthenticatedAdminWebsiteContactRouteImport } from './routes/_authenticated/admin.website.contact'
import { Route as AuthenticatedAdminWebsiteHomeRouteImport } from './routes/_authenticated/admin.website.home'
import { Route as AuthenticatedAdminWebsiteServicesRouteImport } from './routes/_authenticated/admin.website.services'
import { Route as AuthenticatedAdminWebsiteTestimonialsRouteImport } from './routes/_authenticated/admin.website.testimonials'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApieRoute = ApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRouteRoute = EnRouteRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktaiRoute = KontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => rootRouteImport,
} as any)
const PaslaugosRoute = PaslaugosRouteImport.update({
  id: '/paslaugos',
  path: '/paslaugos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumoPolitikaRoute = PrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StraipsniaiRoute = StraipsniaiRouteImport.update({
  id: '/straipsniai',
  path: '/straipsniai',
  getParentRoute: () => rootRouteImport,
} as any)
const TaisyklesRoute = TaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApieIndexRoute = ApieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApieRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnApieRoute = EnApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnKontaktaiRoute = EnKontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnPaslaugosRoute = EnPaslaugosRouteImport.update({
  id: '/paslaugos',
  path: '/paslaugos',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnPrivatumoPolitikaRoute = EnPrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnTaisyklesRoute = EnTaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => EnRouteRoute,
} as any)
const PaslaugosIndexRoute = PaslaugosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaslaugosRoute,
} as any)
const PaslaugosSlugRoute = PaslaugosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PaslaugosRoute,
} as any)
const StraipsniaiIndexRoute = StraipsniaiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StraipsniaiRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInquiriesRoute =
  AuthenticatedAdminInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const EnApieIndexRoute = EnApieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnApieRoute,
} as any)
const EnPaslaugosIndexRoute = EnPaslaugosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnPaslaugosRoute,
} as any)
const EnPaslaugosSlugRoute = EnPaslaugosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnPaslaugosRoute,
} as any)
const AuthenticatedAdminWebsiteAboutRoute =
  AuthenticatedAdminWebsiteAboutRouteImport.update({
    id: '/website/about',
    path: '/website/about',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteContactRoute =
  AuthenticatedAdminWebsiteContactRouteImport.update({
    id: '/website/contact',
    path: '/website/contact',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteHomeRoute =
  AuthenticatedAdminWebsiteHomeRouteImport.update({
    id: '/website/home',
    path: '/website/home',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteServicesRoute =
  AuthenticatedAdminWebsiteServicesRouteImport.update({
    id: '/website/services',
    path: '/website/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteTestimonialsRoute =
  AuthenticatedAdminWebsiteTestimonialsRouteImport.update({
    id: '/website/testimonials',
    path: '/website/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteRouteWithChildren
  '/apie': typeof ApieRouteWithChildren
  '/auth': typeof AuthRoute
  '/kontaktai': typeof KontaktaiRoute
  '/paslaugos': typeof PaslaugosRouteWithChildren
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/straipsniai': typeof StraipsniaiRouteWithChildren
  '/taisykles': typeof TaisyklesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/en/apie': typeof EnApieRouteWithChildren
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/paslaugos': typeof EnPaslaugosRouteWithChildren
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/paslaugos/$slug': typeof PaslaugosSlugRoute
  '/apie/': typeof ApieIndexRoute
  '/en/': typeof EnIndexRoute
  '/paslaugos/': typeof PaslaugosIndexRoute
  '/straipsniai/': typeof StraipsniaiIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/en/paslaugos/$slug': typeof EnPaslaugosSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/en/apie/': typeof EnApieIndexRoute
  '/en/paslaugos/': typeof EnPaslaugosIndexRoute
  '/admin/website/about': typeof AuthenticatedAdminWebsiteAboutRoute
  '/admin/website/contact': typeof AuthenticatedAdminWebsiteContactRoute
  '/admin/website/home': typeof AuthenticatedAdminWebsiteHomeRoute
  '/admin/website/services': typeof AuthenticatedAdminWebsiteServicesRoute
  '/admin/website/testimonials': typeof AuthenticatedAdminWebsiteTestimonialsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontaktai': typeof KontaktaiRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taisykles': typeof TaisyklesRoute
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/paslaugos/$slug': typeof PaslaugosSlugRoute
  '/apie': typeof ApieIndexRoute
  '/en': typeof EnIndexRoute
  '/paslaugos': typeof PaslaugosIndexRoute
  '/straipsniai': typeof StraipsniaiIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/en/paslaugos/$slug': typeof EnPaslaugosSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/en/apie': typeof EnApieIndexRoute
  '/en/paslaugos': typeof EnPaslaugosIndexRoute
  '/admin/website/about': typeof AuthenticatedAdminWebsiteAboutRoute
  '/admin/website/contact': typeof AuthenticatedAdminWebsiteContactRoute
  '/admin/website/home': typeof AuthenticatedAdminWebsiteHomeRoute
  '/admin/website/services': typeof AuthenticatedAdminWebsiteServicesRoute
  '/admin/website/testimonials': typeof AuthenticatedAdminWebsiteTestimonialsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/en': typeof EnRouteRouteWithChildren
  '/apie': typeof ApieRouteWithChildren
  '/auth': typeof AuthRoute
  '/kontaktai': typeof KontaktaiRoute
  '/paslaugos': typeof PaslaugosRouteWithChildren
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/straipsniai': typeof StraipsniaiRouteWithChildren
  '/taisykles': typeof TaisyklesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/en/apie': typeof EnApieRouteWithChildren
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/paslaugos': typeof EnPaslaugosRouteWithChildren
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/paslaugos/$slug': typeof PaslaugosSlugRoute
  '/apie/': typeof ApieIndexRoute
  '/en/': typeof EnIndexRoute
  '/paslaugos/': typeof PaslaugosIndexRoute
  '/straipsniai/': typeof StraipsniaiIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/en/paslaugos/$slug': typeof EnPaslaugosSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/en/apie/': typeof EnApieIndexRoute
  '/en/paslaugos/': typeof EnPaslaugosIndexRoute
  '/_authenticated/admin/website/about': typeof AuthenticatedAdminWebsiteAboutRoute
  '/_authenticated/admin/website/contact': typeof AuthenticatedAdminWebsiteContactRoute
  '/_authenticated/admin/website/home': typeof AuthenticatedAdminWebsiteHomeRoute
  '/_authenticated/admin/website/services': typeof AuthenticatedAdminWebsiteServicesRoute
  '/_authenticated/admin/website/testimonials': typeof AuthenticatedAdminWebsiteTestimonialsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/apie'
    | '/auth'
    | '/kontaktai'
    | '/paslaugos'
    | '/privatumo-politika'
    | '/reset-password'
    | '/sitemap.xml'
    | '/straipsniai'
    | '/taisykles'
    | '/admin'
    | '/en/apie'
    | '/en/kontaktai'
    | '/en/paslaugos'
    | '/en/privatumo-politika'
    | '/en/taisykles'
    | '/paslaugos/$slug'
    | '/apie/'
    | '/en/'
    | '/paslaugos/'
    | '/straipsniai/'
    | '/admin/analytics'
    | '/admin/inquiries'
    | '/admin/settings'
    | '/admin/users'
    | '/en/paslaugos/$slug'
    | '/admin/'
    | '/en/apie/'
    | '/en/paslaugos/'
    | '/admin/website/about'
    | '/admin/website/contact'
    | '/admin/website/home'
    | '/admin/website/services'
    | '/admin/website/testimonials'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kontaktai'
    | '/privatumo-politika'
    | '/reset-password'
    | '/sitemap.xml'
    | '/taisykles'
    | '/en/kontaktai'
    | '/en/privatumo-politika'
    | '/en/taisykles'
    | '/paslaugos/$slug'
    | '/apie'
    | '/en'
    | '/paslaugos'
    | '/straipsniai'
    | '/admin/analytics'
    | '/admin/inquiries'
    | '/admin/settings'
    | '/admin/users'
    | '/en/paslaugos/$slug'
    | '/admin'
    | '/en/apie'
    | '/en/paslaugos'
    | '/admin/website/about'
    | '/admin/website/contact'
    | '/admin/website/home'
    | '/admin/website/services'
    | '/admin/website/testimonials'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/en'
    | '/apie'
    | '/auth'
    | '/kontaktai'
    | '/paslaugos'
    | '/privatumo-politika'
    | '/reset-password'
    | '/sitemap.xml'
    | '/straipsniai'
    | '/taisykles'
    | '/_authenticated/admin'
    | '/en/apie'
    | '/en/kontaktai'
    | '/en/paslaugos'
    | '/en/privatumo-politika'
    | '/en/taisykles'
    | '/paslaugos/$slug'
    | '/apie/'
    | '/en/'
    | '/paslaugos/'
    | '/straipsniai/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/inquiries'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/en/paslaugos/$slug'
    | '/_authenticated/admin/'
    | '/en/apie/'
    | '/en/paslaugos/'
    | '/_authenticated/admin/website/about'
    | '/_authenticated/admin/website/contact'
    | '/_authenticated/admin/website/home'
    | '/_authenticated/admin/website/services'
    | '/_authenticated/admin/website/testimonials'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EnRouteRoute: typeof EnRouteRouteWithChildren
  ApieRoute: typeof ApieRouteWithChildren
  AuthRoute: typeof AuthRoute
  KontaktaiRoute: typeof KontaktaiRoute
  PaslaugosRoute: typeof PaslaugosRouteWithChildren
  PrivatumoPolitikaRoute: typeof PrivatumoPolitikaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StraipsniaiRoute: typeof StraipsniaiRouteWithChildren
  TaisyklesRoute: typeof TaisyklesRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apie': {
      id: '/apie'
      path: '/apie'
      fullPath: '/apie'
      preLoaderRoute: typeof ApieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktai': {
      id: '/kontaktai'
      path: '/kontaktai'
      fullPath: '/kontaktai'
      preLoaderRoute: typeof KontaktaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paslaugos': {
      id: '/paslaugos'
      path: '/paslaugos'
      fullPath: '/paslaugos'
      preLoaderRoute: typeof PaslaugosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/straipsniai': {
      id: '/straipsniai'
      path: '/straipsniai'
      fullPath: '/straipsniai'
      preLoaderRoute: typeof StraipsniaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taisykles': {
      id: '/taisykles'
      path: '/taisykles'
      fullPath: '/taisykles'
      preLoaderRoute: typeof TaisyklesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apie/': {
      id: '/apie/'
      path: '/'
      fullPath: '/apie/'
      preLoaderRoute: typeof ApieIndexRouteImport
      parentRoute: typeof ApieRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/apie': {
      id: '/en/apie'
      path: '/apie'
      fullPath: '/en/apie'
      preLoaderRoute: typeof EnApieRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/kontaktai': {
      id: '/en/kontaktai'
      path: '/kontaktai'
      fullPath: '/en/kontaktai'
      preLoaderRoute: typeof EnKontaktaiRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/paslaugos': {
      id: '/en/paslaugos'
      path: '/paslaugos'
      fullPath: '/en/paslaugos'
      preLoaderRoute: typeof EnPaslaugosRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/privatumo-politika': {
      id: '/en/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/en/privatumo-politika'
      preLoaderRoute: typeof EnPrivatumoPolitikaRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/taisykles': {
      id: '/en/taisykles'
      path: '/taisykles'
      fullPath: '/en/taisykles'
      preLoaderRoute: typeof EnTaisyklesRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/paslaugos/': {
      id: '/paslaugos/'
      path: '/'
      fullPath: '/paslaugos/'
      preLoaderRoute: typeof PaslaugosIndexRouteImport
      parentRoute: typeof PaslaugosRoute
    }
    '/paslaugos/$slug': {
      id: '/paslaugos/$slug'
      path: '/$slug'
      fullPath: '/paslaugos/$slug'
      preLoaderRoute: typeof PaslaugosSlugRouteImport
      parentRoute: typeof PaslaugosRoute
    }
    '/straipsniai/': {
      id: '/straipsniai/'
      path: '/'
      fullPath: '/straipsniai/'
      preLoaderRoute: typeof StraipsniaiIndexRouteImport
      parentRoute: typeof StraipsniaiRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inquiries': {
      id: '/_authenticated/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AuthenticatedAdminInquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/en/apie/': {
      id: '/en/apie/'
      path: '/'
      fullPath: '/en/apie/'
      preLoaderRoute: typeof EnApieIndexRouteImport
      parentRoute: typeof EnApieRoute
    }
    '/en/paslaugos/': {
      id: '/en/paslaugos/'
      path: '/'
      fullPath: '/en/paslaugos/'
      preLoaderRoute: typeof EnPaslaugosIndexRouteImport
      parentRoute: typeof EnPaslaugosRoute
    }
    '/en/paslaugos/$slug': {
      id: '/en/paslaugos/$slug'
      path: '/$slug'
      fullPath: '/en/paslaugos/$slug'
      preLoaderRoute: typeof EnPaslaugosSlugRouteImport
      parentRoute: typeof EnPaslaugosRoute
    }
    '/_authenticated/admin/website/about': {
      id: '/_authenticated/admin/website/about'
      path: '/website/about'
      fullPath: '/admin/website/about'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/contact': {
      id: '/_authenticated/admin/website/contact'
      path: '/website/contact'
      fullPath: '/admin/website/contact'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteContactRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/home': {
      id: '/_authenticated/admin/website/home'
      path: '/website/home'
      fullPath: '/admin/website/home'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteHomeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/services': {
      id: '/_authenticated/admin/website/services'
      path: '/website/services'
      fullPath: '/admin/website/services'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website/testimonials': {
      id: '/_authenticated/admin/website/testimonials'
      path: '/website/testimonials'
      fullPath: '/admin/website/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminInquiriesRoute: typeof AuthenticatedAdminInquiriesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminWebsiteAboutRoute: typeof AuthenticatedAdminWebsiteAboutRoute
  AuthenticatedAdminWebsiteContactRoute: typeof AuthenticatedAdminWebsiteContactRoute
  AuthenticatedAdminWebsiteHomeRoute: typeof AuthenticatedAdminWebsiteHomeRoute
  AuthenticatedAdminWebsiteServicesRoute: typeof AuthenticatedAdminWebsiteServicesRoute
  AuthenticatedAdminWebsiteTestimonialsRoute: typeof AuthenticatedAdminWebsiteTestimonialsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminInquiriesRoute: AuthenticatedAdminInquiriesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminWebsiteAboutRoute: AuthenticatedAdminWebsiteAboutRoute,
  AuthenticatedAdminWebsiteContactRoute: AuthenticatedAdminWebsiteContactRoute,
  AuthenticatedAdminWebsiteHomeRoute: AuthenticatedAdminWebsiteHomeRoute,
  AuthenticatedAdminWebsiteServicesRoute:
    AuthenticatedAdminWebsiteServicesRoute,
  AuthenticatedAdminWebsiteTestimonialsRoute:
    AuthenticatedAdminWebsiteTestimonialsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EnApieRouteChildren {
  EnApieIndexRoute: typeof EnApieIndexRoute
}

const EnApieRouteChildren: EnApieRouteChildren = {
  EnApieIndexRoute: EnApieIndexRoute,
}

const EnApieRouteWithChildren =
  EnApieRoute._addFileChildren(EnApieRouteChildren)

interface EnPaslaugosRouteChildren {
  EnPaslaugosSlugRoute: typeof EnPaslaugosSlugRoute
  EnPaslaugosIndexRoute: typeof EnPaslaugosIndexRoute
}

const EnPaslaugosRouteChildren: EnPaslaugosRouteChildren = {
  EnPaslaugosSlugRoute: EnPaslaugosSlugRoute,
  EnPaslaugosIndexRoute: EnPaslaugosIndexRoute,
}

const EnPaslaugosRouteWithChildren = EnPaslaugosRoute._addFileChildren(
  EnPaslaugosRouteChildren,
)

interface EnRouteRouteChildren {
  EnApieRoute: typeof EnApieRouteWithChildren
  EnKontaktaiRoute: typeof EnKontaktaiRoute
  EnPaslaugosRoute: typeof EnPaslaugosRouteWithChildren
  EnPrivatumoPolitikaRoute: typeof EnPrivatumoPolitikaRoute
  EnTaisyklesRoute: typeof EnTaisyklesRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteRouteChildren: EnRouteRouteChildren = {
  EnApieRoute: EnApieRouteWithChildren,
  EnKontaktaiRoute: EnKontaktaiRoute,
  EnPaslaugosRoute: EnPaslaugosRouteWithChildren,
  EnPrivatumoPolitikaRoute: EnPrivatumoPolitikaRoute,
  EnTaisyklesRoute: EnTaisyklesRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteRouteWithChildren =
  EnRouteRoute._addFileChildren(EnRouteRouteChildren)

interface ApieRouteChildren {
  ApieIndexRoute: typeof ApieIndexRoute
}

const ApieRouteChildren: ApieRouteChildren = {
  ApieIndexRoute: ApieIndexRoute,
}

const ApieRouteWithChildren = ApieRoute._addFileChildren(ApieRouteChildren)

interface PaslaugosRouteChildren {
  PaslaugosSlugRoute: typeof PaslaugosSlugRoute
  PaslaugosIndexRoute: typeof PaslaugosIndexRoute
}

const PaslaugosRouteChildren: PaslaugosRouteChildren = {
  PaslaugosSlugRoute: PaslaugosSlugRoute,
  PaslaugosIndexRoute: PaslaugosIndexRoute,
}

const PaslaugosRouteWithChildren = PaslaugosRoute._addFileChildren(
  PaslaugosRouteChildren,
)

interface StraipsniaiRouteChildren {
  StraipsniaiIndexRoute: typeof StraipsniaiIndexRoute
}

const StraipsniaiRouteChildren: StraipsniaiRouteChildren = {
  StraipsniaiIndexRoute: StraipsniaiIndexRoute,
}

const StraipsniaiRouteWithChildren = StraipsniaiRoute._addFileChildren(
  StraipsniaiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EnRouteRoute: EnRouteRouteWithChildren,
  ApieRoute: ApieRouteWithChildren,
  AuthRoute: AuthRoute,
  KontaktaiRoute: KontaktaiRoute,
  PaslaugosRoute: PaslaugosRouteWithChildren,
  PrivatumoPolitikaRoute: PrivatumoPolitikaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StraipsniaiRoute: StraipsniaiRouteWithChildren,
  TaisyklesRoute: TaisyklesRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
