/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ApieRouteImport } from './routes/apie'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EnRouteRouteImport } from './routes/en/route'
import { Route as KontaktaiRouteImport } from './routes/kontaktai'
import { Route as PrivatumoPolitikaRouteImport } from './routes/privatumo-politika'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TaisyklesRouteImport } from './routes/taisykles'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApieIndexRouteImport } from './routes/apie.index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnApieRouteImport } from './routes/en/apie'
import { Route as EnKontaktaiRouteImport } from './routes/en/kontaktai'
import { Route as EnPrivatumoPolitikaRouteImport } from './routes/en/privatumo-politika'
import { Route as EnTaisyklesRouteImport } from './routes/en/taisykles'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as EnApieIndexRouteImport } from './routes/en/apie.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ApieRoute = ApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRouteRoute = EnRouteRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktaiRoute = KontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumoPolitikaRoute = PrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TaisyklesRoute = TaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApieIndexRoute = ApieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApieRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnApieRoute = EnApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnKontaktaiRoute = EnKontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnPrivatumoPolitikaRoute = EnPrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnTaisyklesRoute = EnTaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => EnRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const EnApieIndexRoute = EnApieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnApieRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteRouteWithChildren
  '/apie': typeof ApieRouteWithChildren
  '/auth': typeof AuthRoute
  '/kontaktai': typeof KontaktaiRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taisykles': typeof TaisyklesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/en/apie': typeof EnApieRouteWithChildren
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/apie/': typeof ApieIndexRoute
  '/en/': typeof EnIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/en/apie/': typeof EnApieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/kontaktai': typeof KontaktaiRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taisykles': typeof TaisyklesRoute
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/apie': typeof ApieIndexRoute
  '/en': typeof EnIndexRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/en/apie': typeof EnApieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/en': typeof EnRouteRouteWithChildren
  '/apie': typeof ApieRouteWithChildren
  '/auth': typeof AuthRoute
  '/kontaktai': typeof KontaktaiRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taisykles': typeof TaisyklesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/en/apie': typeof EnApieRouteWithChildren
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/apie/': typeof ApieIndexRoute
  '/en/': typeof EnIndexRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/en/apie/': typeof EnApieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/apie'
    | '/auth'
    | '/kontaktai'
    | '/privatumo-politika'
    | '/reset-password'
    | '/sitemap.xml'
    | '/taisykles'
    | '/admin'
    | '/en/apie'
    | '/en/kontaktai'
    | '/en/privatumo-politika'
    | '/en/taisykles'
    | '/apie/'
    | '/en/'
    | '/admin/users'
    | '/admin/'
    | '/en/apie/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/kontaktai'
    | '/privatumo-politika'
    | '/reset-password'
    | '/sitemap.xml'
    | '/taisykles'
    | '/en/kontaktai'
    | '/en/privatumo-politika'
    | '/en/taisykles'
    | '/apie'
    | '/en'
    | '/admin/users'
    | '/admin'
    | '/en/apie'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/en'
    | '/apie'
    | '/auth'
    | '/kontaktai'
    | '/privatumo-politika'
    | '/reset-password'
    | '/sitemap.xml'
    | '/taisykles'
    | '/_authenticated/admin'
    | '/en/apie'
    | '/en/kontaktai'
    | '/en/privatumo-politika'
    | '/en/taisykles'
    | '/apie/'
    | '/en/'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/en/apie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EnRouteRoute: typeof EnRouteRouteWithChildren
  ApieRoute: typeof ApieRouteWithChildren
  AuthRoute: typeof AuthRoute
  KontaktaiRoute: typeof KontaktaiRoute
  PrivatumoPolitikaRoute: typeof PrivatumoPolitikaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaisyklesRoute: typeof TaisyklesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apie': {
      id: '/apie'
      path: '/apie'
      fullPath: '/apie'
      preLoaderRoute: typeof ApieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktai': {
      id: '/kontaktai'
      path: '/kontaktai'
      fullPath: '/kontaktai'
      preLoaderRoute: typeof KontaktaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taisykles': {
      id: '/taisykles'
      path: '/taisykles'
      fullPath: '/taisykles'
      preLoaderRoute: typeof TaisyklesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/apie/': {
      id: '/apie/'
      path: '/'
      fullPath: '/apie/'
      preLoaderRoute: typeof ApieIndexRouteImport
      parentRoute: typeof ApieRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/apie': {
      id: '/en/apie'
      path: '/apie'
      fullPath: '/en/apie'
      preLoaderRoute: typeof EnApieRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/kontaktai': {
      id: '/en/kontaktai'
      path: '/kontaktai'
      fullPath: '/en/kontaktai'
      preLoaderRoute: typeof EnKontaktaiRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/privatumo-politika': {
      id: '/en/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/en/privatumo-politika'
      preLoaderRoute: typeof EnPrivatumoPolitikaRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/taisykles': {
      id: '/en/taisykles'
      path: '/taisykles'
      fullPath: '/en/taisykles'
      preLoaderRoute: typeof EnTaisyklesRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/en/apie/': {
      id: '/en/apie/'
      path: '/'
      fullPath: '/en/apie/'
      preLoaderRoute: typeof EnApieIndexRouteImport
      parentRoute: typeof EnApieRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface EnApieRouteChildren {
  EnApieIndexRoute: typeof EnApieIndexRoute
}

const EnApieRouteChildren: EnApieRouteChildren = {
  EnApieIndexRoute: EnApieIndexRoute,
}

const EnApieRouteWithChildren =
  EnApieRoute._addFileChildren(EnApieRouteChildren)

interface EnRouteRouteChildren {
  EnApieRoute: typeof EnApieRouteWithChildren
  EnKontaktaiRoute: typeof EnKontaktaiRoute
  EnPrivatumoPolitikaRoute: typeof EnPrivatumoPolitikaRoute
  EnTaisyklesRoute: typeof EnTaisyklesRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteRouteChildren: EnRouteRouteChildren = {
  EnApieRoute: EnApieRouteWithChildren,
  EnKontaktaiRoute: EnKontaktaiRoute,
  EnPrivatumoPolitikaRoute: EnPrivatumoPolitikaRoute,
  EnTaisyklesRoute: EnTaisyklesRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteRouteWithChildren =
  EnRouteRoute._addFileChildren(EnRouteRouteChildren)

interface ApieRouteChildren {
  ApieIndexRoute: typeof ApieIndexRoute
}

const ApieRouteChildren: ApieRouteChildren = {
  ApieIndexRoute: ApieIndexRoute,
}

const ApieRouteWithChildren = ApieRoute._addFileChildren(ApieRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EnRouteRoute: EnRouteRouteWithChildren,
  ApieRoute: ApieRouteWithChildren,
  AuthRoute: AuthRoute,
  KontaktaiRoute: KontaktaiRoute,
  PrivatumoPolitikaRoute: PrivatumoPolitikaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaisyklesRoute: TaisyklesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
