DROP TABLE IF EXISTS public.signed_contracts CASCADE;
DROP TABLE IF EXISTS public.contract_templates CASCADE;
DROP TABLE IF EXISTS public.invoices CASCADE;
DROP TABLE IF EXISTS public.payment_transactions CASCADE;
DROP TABLE IF EXISTS public.booking_notifications CASCADE;
DROP TABLE IF EXISTS public.bookings CASCADE;
DROP TABLE IF EXISTS public.housekeeping_comments CASCADE;
DROP TABLE IF EXISTS public.housekeeping_tasks CASCADE;
DROP TABLE IF EXISTS public.room_status CASCADE;
DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.property_documents CASCADE;
DROP TABLE IF EXISTS public.property_events CASCADE;
DROP TABLE IF EXISTS public.property_investments CASCADE;
DROP TABLE IF EXISTS public.property_maintenance CASCADE;
DROP TABLE IF EXISTS public.property_settings CASCADE;
DROP TABLE IF EXISTS public.properties CASCADE;
DROP TABLE IF EXISTS public.car_investments CASCADE;
DROP TABLE IF EXISTS public.car_maintenance CASCADE;
DROP TABLE IF EXISTS public.cars CASCADE;
DROP TABLE IF EXISTS public.api_request_log CASCADE;
DROP TABLE IF EXISTS public.api_clients CASCADE;
DROP TABLE IF EXISTS public.app_secrets CASCADE;

DROP FUNCTION IF EXISTS public.admin_get_door_code(uuid);
DROP FUNCTION IF EXISTS public.cancel_expired_pending_bookings();
DROP FUNCTION IF EXISTS public.claim_invoice_number();
DROP FUNCTION IF EXISTS public.create_room_status_for_property();
DROP FUNCTION IF EXISTS public.ensure_single_active_template();
DROP FUNCTION IF EXISTS public.get_active_booked_dates();
DROP FUNCTION IF EXISTS public.get_property_booked_dates(uuid);
DROP FUNCTION IF EXISTS public.set_api_clients_updated_at();
DROP FUNCTION IF EXISTS public.set_booking_number();
DROP FUNCTION IF EXISTS public.set_property_settings_updated_at();
DROP FUNCTION IF EXISTS public.touch_room_status_updated_at();
